var box = document.getElementById('myCanvas');
var lienzo = box.getContext('2d');
// var blacks = '#64dd17';
var blacks = 'black';

var  first = 0;
var  second = 0;
var  third = 600;
var  fourth = 600;


	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;

	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;

	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;

	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;

	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;

	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;

	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;

	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;

	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;

	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
	lienzo.strokeStyle = blacks;
	lienzo.beginPath();
	lienzo.lineWidth = 1;
	lienzo.strokeRect(first,second,third,fourth);
	lienzo.stroke();
	lienzo.closePath();
	first = first + 4;
	second = second + 4;
	third = third - 8;
	fourth = fourth - 8;
